# -*- mode: ruby -*-
# vi: set ft=ruby :

# Docs: https://docs.vagrantup.com
Vagrant.configure(2) do |config|
  # Box repo: https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/vivid64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.0.0"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    vb.memory = "1024"
  end

  # Use vagrant sync to force reloading
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end
