# probr-core, django app
web:
   build: .
   command: /bin/bash -c "/scripts/wait-for-it.sh postgres:5432 -- /usr/local/bin/ep -v /code/probr/settings.py; python /code/manage.py migrate; python /code/manage.py loaddata /code/initial.json; supervisord -n"
   ports:
     - "8001:8001"
     - "8002:8002"
   volumes_from:
     - dataprobr
   links:
     - postgres:postgres
     - redis:redis


# probr-core, websockets
worker:
   build: .
   command: /bin/bash -c "/scripts/wait-for-it.sh postgres:5432 -- /usr/local/bin/ep -v /code/probr/settings.py; python /code/manage.py migrate; celery worker --workdir /code/ -A probr -S django"
   volumes_from:
     - dataprobr
   links:
     - postgres:postgres
     - redis:redis

# database container
postgres:
   image: postgres:9.4.5
   environment:
     POSTGRES_USER: probr
     POSTGRES_PASSWORD: probr

# redis container
redis:
   image: redis:2.8.19

# data container for probr
dataprobr:
  image: cogniteev/echo
  volumes:
    - ./media:/code/media